group: build
steps:
  - name: ray-core-build
    label: "wanda: core binary parts py{{matrix}} (x86_64)"
    wanda: ci/docker/ray-core.wanda.yaml
    matrix:
      - "3.10"
      - "3.11"
      - "3.12"
      - "3.13"
    env:
      PYTHON_VERSION: "{{matrix}}"
      ARCH_SUFFIX: ""
      HOSTTYPE: "x86_64"
      MANYLINUX_VERSION: "260103.868e54c"
    tags: release_wheels

  - name: ray-dashboard-build
    label: "wanda: dashboard"
    wanda: ci/docker/ray-dashboard.wanda.yaml
    env:
      HOSTTYPE: "x86_64"
      MANYLINUX_VERSION: "260103.868e54c"
    tags: release_wheels

  - name: ray-java-build
    label: "wanda: java build (x86_64)"
    wanda: ci/docker/ray-java.wanda.yaml
    tags:
      - release_wheels
      - java
      - oss
    env:
      ARCH_SUFFIX: ""
      HOSTTYPE: "x86_64"
      MANYLINUX_VERSION: "260103.868e54c"

  - name: ray-wheel-build
    label: "wanda: wheel py{{matrix}} (x86_64)"
    wanda: ci/docker/ray-wheel.wanda.yaml
    matrix:
      - "3.10"
      - "3.11"
      - "3.12"
      - "3.13"
    env:
      PYTHON_VERSION: "{{matrix}}"
      ARCH_SUFFIX: ""
      HOSTTYPE: "x86_64"
      MANYLINUX_VERSION: "260103.868e54c"
    tags:
      - release_wheels
      - linux_wheels
      - oss
    depends_on:
      - ray-core-build
      - ray-java-build
      - ray-dashboard-build

  - name: ray-cpp-core-build
    label: "wanda: cpp core py{{matrix}} (x86_64)"
    wanda: ci/docker/ray-cpp-core.wanda.yaml
    matrix:
      - "3.10"
      - "3.11"
      - "3.12"
    env:
      PYTHON_VERSION: "{{matrix}}"
      ARCH_SUFFIX: ""
      HOSTTYPE: "x86_64"
      MANYLINUX_VERSION: "260103.868e54c"
    tags:
      - release_wheels
      - oss

  - name: ray-cpp-wheel-build
    label: "wanda: cpp wheel py{{matrix}} (x86_64)"
    wanda: ci/docker/ray-cpp-wheel.wanda.yaml
    matrix:
      - "3.10"
      - "3.11"
      - "3.12"
    env:
      PYTHON_VERSION: "{{matrix}}"
      ARCH_SUFFIX: ""
      HOSTTYPE: "x86_64"
      MANYLINUX_VERSION: "260103.868e54c"
    tags:
      - release_wheels
      - linux_wheels
      - oss
    depends_on:
      - ray-core-build
      - ray-cpp-core-build
      - ray-java-build
      - ray-dashboard-build

  # Upload wheels to S3
  # Gating: only on releases/* OR (master AND nightly)
  - label: ":s3: upload: wheel py{{matrix}} (x86_64)"
    key: linux_wheels_upload
    if: build.branch =~ /^releases\// || (build.branch == "master" && build.env("RAYCI_SCHEDULE") == "nightly")
    instance_type: small
    commands:
      # Extract wheel from wanda image (Wanda cache in ECR)
      - wanda_image="$RAYCI_WORK_REPO:$RAYCI_BUILD_ID-ray-wheel-py{{matrix}}"
      - container_id=$(docker create $wanda_image)
      - mkdir -p /tmp/wheels
      - docker cp ${container_id}:/ /tmp/wheels/
      - docker rm ${container_id}
      - mkdir -p .whl
      - mv /tmp/wheels/*.whl .whl/
      - ./ci/build/copy_build_artifacts.sh wheel
    matrix:
      - "3.10"
      - "3.11"
      - "3.12"
      - "3.13"
    depends_on:
      - ray-wheel-build
    tags:
      - release_wheels
      - skip-on-premerge

  # Upload cpp wheels to S3
  # Gating: only on releases/* OR (master AND nightly)
  - label: ":s3: upload: cpp wheel py{{matrix}} (x86_64)"
    key: linux_cpp_wheels_upload
    if: build.branch =~ /^releases\// || (build.branch == "master" && build.env("RAYCI_SCHEDULE") == "nightly")
    instance_type: small
    commands:
      # Extract cpp wheel from wanda image (Wanda cache in ECR)
      - wanda_image="$RAYCI_WORK_REPO:$RAYCI_BUILD_ID-ray-cpp-wheel-py{{matrix}}"
      - container_id=$(docker create $wanda_image)
      - mkdir -p /tmp/wheels
      - docker cp ${container_id}:/ /tmp/wheels/
      - docker rm ${container_id}
      - mkdir -p .whl
      - mv /tmp/wheels/*.whl .whl/
      - ./ci/build/copy_build_artifacts.sh wheel
    matrix:
      - "3.10"
      - "3.11"
      - "3.12"
    depends_on:
      - ray-cpp-wheel-build
    tags:
      - release_wheels
      - skip-on-premerge

  # Validate wheel can be extracted and installed (runs on PRs)
  - label: ":mag: validate: wheel py{{matrix}} (x86_64)"
    key: linux_wheels_validate
    instance_type: small
    commands:
      - wanda_image="$RAYCI_WORK_REPO:$RAYCI_BUILD_ID-ray-wheel-py{{matrix}}"
      - container_id=$(docker create $wanda_image)
      - mkdir -p /tmp/wheels
      - docker cp ${container_id}:/ /tmp/wheels/
      - docker rm ${container_id}
      - ls -la /tmp/wheels/*.whl
      - pip install /tmp/wheels/*.whl
      - python -c "import ray; print('ray version:', ray.__version__)"
    matrix:
      - "3.10"
    depends_on:
      - ray-wheel-build
    tags:
      - release_wheels

  - label: ":tapioca: build: jar"
    key: java_wheels
    tags:
      - java
      - oss
    instance_type: medium
    commands:
      - ./ci/build/build-manylinux-ray.sh
      - ./ci/build/build-manylinux-jar.sh
      - ./ci/build/copy_build_artifacts.sh jar
    depends_on: manylinux-x86_64
    job_env: manylinux-x86_64

  - label: ":tapioca: build: ray py{{matrix}} docker (x86_64)"
    key: ray_images
    tags:
      - python_dependencies
      - docker
      - oss
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- docker --python-version {{matrix}}
        --platform cu11.7.1-cudnn8 --platform cu11.8.0-cudnn8
        --platform cu12.1.1-cudnn8 --platform cu12.3.2-cudnn9
        --platform cu12.4.1-cudnn --platform cu12.5.1-cudnn
        --platform cu12.6.3-cudnn --platform cu12.8.1-cudnn
        --platform cu12.9.1-cudnn
        --platform cpu
        --image-type ray --upload
    depends_on:
      - manylinux-x86_64
      - forge
      - raycudabase
      - raycpubase
    matrix:
      - "3.10"
      - "3.11"
      - "3.12"

  - label: ":tapioca: build: ray-extra py{{matrix}} docker (x86_64)"
    key: ray_extra_images
    tags:
      - python_dependencies
      - docker
      - oss
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- docker --python-version {{matrix}}
        --platform cu11.7.1-cudnn8 --platform cu11.8.0-cudnn8
        --platform cu12.1.1-cudnn8 --platform cu12.3.2-cudnn9
        --platform cu12.4.1-cudnn --platform cu12.5.1-cudnn
        --platform cu12.6.3-cudnn --platform cu12.8.1-cudnn
        --platform cu12.9.1-cudnn
        --platform cpu
        --image-type ray-extra --upload
    depends_on:
      - manylinux-x86_64
      - forge
      - raycpubaseextra
      - raycudabaseextra
    matrix:
      - "3.10"
      - "3.11"
      - "3.12"

  - label: ":tapioca: build: ray-llm py{{matrix}} docker (x86_64)"
    tags:
      - python_dependencies
      - docker
      - oss
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- docker --python-version {{matrix}}
        --platform cu12.8.1-cudnn --image-type ray-llm --upload
    depends_on:
      - manylinux-x86_64
      - forge
      - ray-llmbase
    matrix:
      - "3.11"

  - label: ":tapioca: build: ray-llm-extra py{{matrix}} docker (x86_64)"
    tags:
      - python_dependencies
      - docker
      - oss
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- docker --python-version {{matrix}}
        --platform cu12.8.1-cudnn --image-type ray-llm-extra --upload
    depends_on:
      - manylinux-x86_64
      - forge
      - ray-llmbaseextra
    matrix:
      - "3.11"

  - label: ":tapioca: smoke test build-docker.sh"
    tags:
      - python_dependencies
      - docker
      - oss
    instance_type: medium
    soft_fail: true
    commands:
      - export WHEEL_URL="https://files.pythonhosted.org/packages/93/f1/9108c4f878e3cacb767b7dfbbc3a26537c79ab516d2530b9f63b558ba4bb/ray-2.44.1-cp310-cp310-manylinux2014_x86_64.whl"
      - export CPP_WHEEL_URL="https://files.pythonhosted.org/packages/d3/cf/ef6d5a9a688001f73e4749c48f840455ecec11acde982eb70f387b0dc445/ray_cpp-2.44.1-cp310-cp310-manylinux2014_x86_64.whl"
      - bash build-docker.sh --progress-plain
      - docker run -ti --rm rayproject/ray:dev python -c "import ray; print(ray.__version__)"
    depends_on:
      - forge

  - label: ":tapioca: generate nightly indexes"
    instance_type: small
    tags:
      - docker
      - oss
      - skip-on-premerge
    commands:
      - bazel run .buildkite:copy_files -- --destination docker_login
      - bazel run //ci/ray_ci/automation:generate_index -- --prefix nightly
    depends_on:
      - ray_images
      - ray_images_aarch64
      - forge
